// The compliance report endpoint's contract: the report itself, the window it
// covers, and the facts a store hands over before it is built.
//
// Split from compliance_report.go -- the endpoint that decides what happens to a
// request -- for the 300-line ceiling this project holds every file to, and along
// the same line Phase 19's compliance_types.go drew: everything here is a name
// two packages agree on (internal/ledger returns ReportFacts and fills the
// fields the SQL can answer), while the handler and the builder next door are the
// only things that read a request or write a response.
package plane

import (
	"time"
)

// complianceReportRoute is the compliance report endpoint's path, referenced by
// both the route registration and the handler's own documentation. It is also
// the endpoint name every access record for this route carries, so the two
// cannot drift.
const complianceReportRoute = "/v2/compliance/report"

// Article50Statement is the statement every report carries, verbatim.
//
// It is a constant rather than something an implementation builds, because it is
// the report's own description of what it is and is not: a client, an auditor,
// and a court all have to see the identical text, and a compliant-sounding
// paraphrase generated per deployment is exactly the drift this prevents. Both
// formats get it from this one value (the JSON field and the PDF template), so
// the two renderings cannot disagree about what the report claims.
//
// The name follows the brief's own naming (Article 50 of Regulation (EU)
// 2024/1689 concerns transparency obligations); the text itself makes no legal
// claim, which is the point of its second half.
const Article50Statement = "This report is generated by Synapse Context Compiler, which provides cryptographically signed, tamper-evident audit trails of all memory compilation decisions made by AI agents in this organisation. Each compilation event is logged with its full decision trace, memory provenance, scoring rationale, and chain integrity verification. DISCLAIMER: This report provides technical traceability infrastructure. It does not constitute legal advice or guarantee regulatory compliance with Regulation (EU) 2024/1689 or any other instrument. Consult qualified legal counsel regarding your organisation's specific obligations under the EU AI Act."

// ReportWindow is the period a report covers: an inclusive range whose halves
// may each be open.
//
// The two times are pointers for the reason AuditFilter's are: "no since" and
// "since the zero time" are different requests, and the zero time is a value a
// caller can legitimately name. A half that is unset means the report reaches as
// far as that tenant's ledger does -- there is deliberately no default window,
// because a report that silently covered an unasked-for 30 days would answer a
// different question than the one it printed on its own header.
type ReportWindow struct {
	// Since, when set, is the inclusive lower bound on created_at.
	Since *time.Time
	// Until, when set, is the inclusive upper bound on created_at.
	Until *time.Time
}

// ReportFacts is the window's raw material, as stored: every ledger row the
// window holds, plus the metering totals the window holds.
//
// It is the seam between the two halves of this endpoint. The SQL lives on the
// other side of it (internal/ledger owns the tables and their read paths, and
// the HTTP package holds no database handle); everything that decides what the
// numbers *mean* lives on this side and is a pure function of these values (see
// compliance_report_build.go), which is what lets the arithmetic be tested
// without a database.
//
// Rows carry the trace exactly as it was signed -- still a string at this layer,
// parsed by the builder -- because the shape a client sees is this package's
// contract and not the store's.
type ReportFacts struct {
	// Rows is every entry the window matches, newest first. Always non-nil.
	Rows []AuditRow
	// Usage is what the metering table holds for the window. See UsageTotals.
	Usage UsageTotals
}

// UsageTotals is one tenant's metering totals for a window: how many
// compilations it recorded, and their mean reduction.
//
// It is a struct with HasRows rather than a pointer, because "the metering table
// has no rows for this window" is the ordinary state today -- nothing writes
// usage_events until the metering phase lands -- and it is not the same statement
// as "the mean reduction was zero". The summary's two metering-facing numbers
// fall back to the signed ledger when this is false, and the report says which
// source it used. See buildComplianceReport.
type UsageTotals struct {
	// Compilations is how many rows the window holds.
	Compilations int
	// AvgReductionPct is their mean reduction_pct. Zero when Compilations is
	// zero, which HasRows is what distinguishes it from a measured zero.
	AvgReductionPct float64
	// HasRows reports whether the window held any rows at all.
	HasRows bool
}

// ComplianceReport is the body of GET /v2/compliance/report, in both formats:
// the JSON document and, field for field, the HTML-to-PDF rendering of the same
// value (see compliance_report_pdf.go).
//
// Sections rather than a flat list, because that is how a compliance officer
// reads it: what this covers, what happened, whose memory it was, how
// contradictions and supersessions were handled, whether the record is intact,
// and finally what the report does and does not claim.
type ComplianceReport struct {
	// Header identifies the report: whose data it is, over what period, when it
	// was generated, and by which build.
	Header ComplianceReportHeader `json:"header"`
	// Summary is the period's volume: compilations, memories used, and how much
	// context the compiler removed on the way in.
	Summary ComplianceReportSummary `json:"summary"`
	// MemoryTypeBreakdown is the share of used memories per memory type, as a
	// percentage of all memories used in the period. Always non-nil, so an empty
	// period marshals as {} rather than null.
	MemoryTypeBreakdown map[string]float64 `json:"memory_type_breakdown"`
	// GlobalBrain covers memories that crossed an agent boundary.
	GlobalBrain ComplianceReportGlobalBrain `json:"global_brain"`
	// ConflictResolution covers contradictions the write path detected.
	ConflictResolution ComplianceReportConflictResolution `json:"conflict_resolution"`
	// Supersession covers memories a newer memory replaced.
	Supersession ComplianceReportSupersession `json:"supersession"`
	// ChainIntegrity is the audit chain's verdict, walked over the tenant's
	// whole chain rather than over the period alone.
	ChainIntegrity ComplianceReportChainIntegrity `json:"chain_integrity"`
	// Article50Statement is Article50Statement, carried in the body so a client
	// that stores only the JSON keeps the statement that came with it.
	Article50Statement string `json:"article_50_statement"`
}

// ComplianceReportHeader says whose data this is and what it covers.
type ComplianceReportHeader struct {
	// TenantID is the verified token's own tenant. There is no request value
	// that can name another one, so this field can only ever echo the caller.
	TenantID string `json:"tenant_id"`
	// Period is the requested window, echoed back with unset halves as null so
	// the report never implies a bound the caller did not ask for.
	Period ComplianceReportPeriod `json:"period"`
	// GeneratedAt is when this report was built, in UTC.
	GeneratedAt time.Time `json:"generated_at"`
	// SynapseVersion is the build that generated it (plane.Version), so a
	// report can be tied to the software that produced it.
	SynapseVersion string `json:"synapse_version"`
}

// ComplianceReportPeriod is the report's window, as requested.
type ComplianceReportPeriod struct {
	// Since is the inclusive lower bound, or null for "the whole ledger".
	Since *time.Time `json:"since"`
	// Until is the inclusive upper bound, or null for "up to now".
	Until *time.Time `json:"until"`
}

// ComplianceReportSummary is the period's volume.
//
// TotalCompilations and AvgReductionPct are read from the metering table when it
// has rows for the window and fall back to the signed ledger's own traces when it
// does not; the two are noted here because a report whose reduction reads 0.0 has
// to be explainable (see buildComplianceReport).
type ComplianceReportSummary struct {
	// TotalCompilations is how many compilations the period holds: the metering
	// count when usage_events has rows for the window, otherwise one per signed
	// ledger entry.
	TotalCompilations int `json:"total_compilations"`
	// TotalMemoriesUsed is the sum of the traces' own memories_compiled -- the
	// compiler's count of what reached the context, not a recount of the
	// recorded array.
	TotalMemoriesUsed int `json:"total_memories_used"`
	// AvgReductionPct is the mean reduction percentage: the metering mean when
	// usage_events has rows for the window, otherwise the mean of the ledger's
	// recorded traces. Rounded to two decimals.
	AvgReductionPct float64 `json:"avg_reduction_pct"`
}

// ComplianceReportGlobalBrain covers memories that crossed an agent boundary: the
// Global Brain's contribution to this tenant's contexts.
type ComplianceReportGlobalBrain struct {
	// CrossAgentRetrievals counts memory retrievals whose memory was written by
	// an agent other than the one that assembled the context, summed over the
	// period's traces: an event count, not a distinct-memory count, because
	// "how often did another agent's memory show up" is the question this
	// answers.
	CrossAgentRetrievals int `json:"cross_agent_retrievals"`
	// UniqueContributingAgents is how many distinct agents those retrievals
	// came from: an unattributed memory contributes to no agent.
	UniqueContributingAgents int `json:"unique_contributing_agents"`
}

// ComplianceReportConflictResolution covers contradictions the write path
// detected while this tenant's memories were being written.
type ComplianceReportConflictResolution struct {
	// ContradictionsDetected counts distinct memories that introduced a
	// contradiction. The pair's older half (marked superseded_candidate) is
	// deliberately not counted as a second detection, and a memory that appears
	// in several traces is counted once.
	ContradictionsDetected int `json:"contradictions_detected"`
}

// ComplianceReportSupersession covers memories a newer memory replaced.
type ComplianceReportSupersession struct {
	// MemoriesSuperseded counts distinct memories that were replaced by another
	// memory in the period, counted once each however many traces they appear in.
	MemoriesSuperseded int `json:"memories_superseded"`
}

// ComplianceReportChainIntegrity is the audit chain's verdict.
type ComplianceReportChainIntegrity struct {
	// Valid is true only when every entry of the tenant's chain recomputed to
	// its stored hash under the tenant's own secret and chained from its
	// predecessor. It covers the *whole* chain, not EntriesInPeriod: a report
	// that certified only the rows it happened to read would certify nothing.
	Valid bool `json:"valid"`
	// LastVerifiedAt is when that walk ran -- this request's own verification,
	// which is why the report can be handed over as evidence of a check rather
	// than of a claim.
	LastVerifiedAt time.Time `json:"last_verified_at"`
	// EntriesInPeriod is how many chain entries the report's window covers.
	EntriesInPeriod int `json:"entries_in_period"`
}

// pdfToolUnavailableResponse is the 503 body when no HTML-to-PDF renderer is
// installed. It carries the generic error code plus a message naming the fix,
// because this is the one failure on this route a caller can act on by
// themselves.
type pdfToolUnavailableResponse struct {
	Error   string `json:"error"`
	Message string `json:"message"`
}
