package embedder

import (
	"reflect"
	"testing"
)

// Reference values in this file were generated by loading the actual
// models/all-MiniLM-L6-v2/vocab.txt into Python's real
// transformers.BertTokenizer (do_lower_case=true) and encoding each test
// sentence. This is ground truth, not assumed - if our Go tokenizer
// disagrees with these values, the Go implementation is wrong, not the
// test.
func TestWordPieceTokenizerMatchesReference(t *testing.T) {
	tok, err := NewWordPieceTokenizer("../../models/all-MiniLM-L6-v2/vocab.txt")
	if err != nil {
		t.Fatalf("failed to load tokenizer: %v", err)
	}

	// Confirm special token IDs match the real vocab.txt exactly.
	if tok.clsTokenID != 101 {
		t.Errorf("expected [CLS]=101, got %d", tok.clsTokenID)
	}
	if tok.sepTokenID != 102 {
		t.Errorf("expected [SEP]=102, got %d", tok.sepTokenID)
	}
	if tok.unkTokenID != 100 {
		t.Errorf("expected [UNK]=100, got %d", tok.unkTokenID)
	}
	if tok.padTokenID != 0 {
		t.Errorf("expected [PAD]=0, got %d", tok.padTokenID)
	}

	tests := []struct {
		name              string
		input             string
		seqLen            int
		expectedInputIDs  []int64
		expectedAttnMask  []int64
	}{
		{
			name:   "simple sentence with punctuation",
			input:  "Hello world, this is a test.",
			seqLen: 10,
			expectedInputIDs: []int64{101, 7592, 2088, 1010, 2023, 2003, 1037, 3231, 1012, 102},
			expectedAttnMask: []int64{1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
		},
		{
			name:   "nil pointer error - exercises subword splitting (ni + ##l)",
			input:  "I have a nil pointer error in my code",
			seqLen: 12,
			expectedInputIDs: []int64{101, 1045, 2031, 1037, 9152, 2140, 20884, 7561, 1999, 2026, 3642, 102},
			expectedAttnMask: []int64{1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1},
		},
		{
			name:   "single whole-vocabulary word, no splitting needed",
			input:  "unbelievable",
			seqLen: 3,
			expectedInputIDs: []int64{101, 23653, 102},
			expectedAttnMask: []int64{1, 1, 1},
		},
		{
			name:   "hyphenated unknown word - exercises subword splitting and punctuation isolation",
			input:  "COVID-19 affected millions",
			seqLen: 8,
			expectedInputIDs: []int64{101, 2522, 17258, 1011, 2539, 5360, 8817, 102},
			expectedAttnMask: []int64{1, 1, 1, 1, 1, 1, 1, 1},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			inputIDs, attentionMask, tokenTypeIDs := tok.Encode(tt.input, tt.seqLen)

			if !reflect.DeepEqual(inputIDs, tt.expectedInputIDs) {
				t.Errorf("input_ids mismatch for %q:\n  got:      %v\n  expected: %v", tt.input, inputIDs, tt.expectedInputIDs)
			}
			if !reflect.DeepEqual(attentionMask, tt.expectedAttnMask) {
				t.Errorf("attention_mask mismatch for %q:\n  got:      %v\n  expected: %v", tt.input, attentionMask, tt.expectedAttnMask)
			}
			// token_type_ids should always be all zeros for single-sentence input.
			for i, v := range tokenTypeIDs {
				if v != 0 {
					t.Errorf("token_type_ids[%d] = %d, expected 0 (single-sentence input)", i, v)
				}
			}
		})
	}
}

// TestWordPieceTokenizerPadding confirms padding/truncation behavior
// independently of exact token values, since the reference tests above
// already use exact-fit seqLen values.
func TestWordPieceTokenizerPadding(t *testing.T) {
	tok, err := NewWordPieceTokenizer("../../models/all-MiniLM-L6-v2/vocab.txt")
	if err != nil {
		t.Fatalf("failed to load tokenizer: %v", err)
	}

	// "hi" -> [CLS] hi [SEP] = 3 real tokens, padded to seqLen=10 means
	// 7 padding slots with attention_mask=0 and inputID=[PAD]=0.
	inputIDs, attentionMask, _ := tok.Encode("hi", 10)

	if len(inputIDs) != 10 {
		t.Fatalf("expected inputIDs length 10, got %d", len(inputIDs))
	}

	realTokenCount := 0
	for _, m := range attentionMask {
		if m == 1 {
			realTokenCount++
		}
	}
	if realTokenCount != 3 {
		t.Errorf("expected 3 real tokens (CLS + hi + SEP), got %d", realTokenCount)
	}

	for i := realTokenCount; i < 10; i++ {
		if inputIDs[i] != 0 {
			t.Errorf("expected padding inputID=0 at position %d, got %d", i, inputIDs[i])
		}
		if attentionMask[i] != 0 {
			t.Errorf("expected attention_mask=0 at padded position %d, got %d", i, attentionMask[i])
		}
	}
}